config/routes.rb
Rails.application.routes.draw do
  root 'games#new'
  get 'new', to: 'games#new', as: :newpage
  post 'score', to: 'games#score'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require 'json'
  require 'open-uri'

  def new
    @letters = ('A'..'Z').to_a.sample(10)
  end

  def score
    @mot = params[:mot].chars
    @letters = params[:letters]
    @message = @letters.split(" ")
    @message2 = @letters.split(" ")

    @mot.each do |mot, index|
      if @message2.include? "#{@mot}"
        @result = true
        # @message2.delete_at(index)
      else
        @result = false
      end
      # binding.pry
    end

    if @result
      url = "https://wagon-dictionary.herokuapp.com/#{@mot.join}"
      user_serialized = open(url).read
      user = JSON.parse(user_serialized)

      if user['found'] == true
        @message = "english"
      else
        @message = "not english"
      end

    else
      @message = "Sorry but TEST cant be built out of #{@letters}"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New game</h1>
<p>Find me in app/views/games/new.html.erb</p>
<p><%= @letters %><br/><br/><br/></p>

<p> What is the longest word you can find?</p>

<form action="/score" method="post">
  <%= hidden_field_tag :letters, @letters %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="input-group">
    <input type="text" class="form-control" name="mot" >
    <span class="input-group-btn">
      <button class="btn btn-primary" type="submit" value="Play">Play</button>
    </span>
  </div>
</form>

app/views/games/score.html.erb
<h1>Result</h1>
<h1><%= @result %></h1>
<p><%= @message%></p>
<p><%= link_to "Play again", newpage_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>